package io.github.mattiacozzolino.cvascode.cli;

import io.github.mattiacozzolino.cvascode.config.ConfigurationException;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;

import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.concurrent.Callable;

@Command(name = "init", description = "Create a ready-to-edit resume workspace for a new candidate.")
public final class InitCommand implements Callable<Integer> {
    @Option(names = "--target", required = true, description = "Target directory, for example ./my-resume.")
    private Path target;

    @Option(names = "--force", description = "Overwrite files generated by init when they already exist.")
    private boolean force;

    @Override
    public Integer call() throws IOException {
        List<TemplateCopy> copies = List.of(
                new TemplateCopy("init/candidate.yaml", target.resolve("config/candidate.yaml")),
                new TemplateCopy("init/private.yaml", target.resolve("config/private.yaml")),
                new TemplateCopy("init/resume.yaml", target.resolve("config/resume.yaml")),
                new TemplateCopy("init/cover-letter.yaml", target.resolve("config/cover-letter.yaml")),
                new TemplateCopy("init/application.example.yaml", target.resolve("config/application.example.yaml")),
                new TemplateCopy("init/settings.yaml", target.resolve("config/settings.yaml")),
                new TemplateCopy("init/README.md", target.resolve("README.md")),
                new TemplateCopy("init/assets/photo-placeholder.png", target.resolve("assets/photo-placeholder.png"))
        );

        for (TemplateCopy copy : copies) {
            copy(copy.resource(), copy.target());
        }
        Files.createDirectories(target.resolve("assets"));
        Files.createDirectories(target.resolve("output"));
        System.out.println("Created resume workspace: " + target);
        System.out.println("Next: edit YAML files in " + target.resolve("config") + " and run generate-all.");
        return 0;
    }

    private void copy(String resource, Path destination) throws IOException {
        if (!force && Files.exists(destination)) {
            throw new ConfigurationException("Refusing to overwrite existing file: " + destination
                    + ". Re-run init with --force if you want to replace generated files.");
        }
        Files.createDirectories(destination.getParent());
        try (InputStream input = Thread.currentThread().getContextClassLoader().getResourceAsStream(resource)) {
            if (input == null) {
                throw new ConfigurationException("Missing init template resource: " + resource);
            }
            Files.copy(input, destination, java.nio.file.StandardCopyOption.REPLACE_EXISTING);
        }
    }

    private record TemplateCopy(String resource, Path target) {
    }
}
